[package]
name = "learn-multiply"
version = "0.1.0"
authors = ["Mezner <mezner@russellmyers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rand = "0.7"
text_io = "0.1.7"
termcolor = "1"